### ISSUE TITLE
PPParameters not working when adding an nzb file

### ISSUE THREAD

**Issue by F4n4t** [golift/nzbget#7]
First of all, thank you for providing this great library. I needed something to interact with NZBGet, and it saved me some time today.

I'm currently facing an issue; perhaps I'm making a mistake somewhere, or there might be a bug in the code.
My intention was to configure certain post-processing parameters, but for some reason, they are being ignored.
I tried the example Python snippet from https://nzbget.net/api/append, and it worked successfully.

Here's an example of the code I'm using:

```go
package main

import (
	"encoding/base64"
	"fmt"
	"golift.io/nzbget"
	"os"
	"path/filepath"
)

func main() {
	nzbFile := "test.nzb"
	nzbContent, err := os.ReadFile(nzbFile)
	if err != nil {
		panic(err)
	}

	nzb := nzbget.New(&nzbget.Config{
		URL: "http://localhost:6789/",
		User: "userName",
		Pass: "passWord",
	})

	fmt.Println(nzb.Version())

	input := &nzbget.AppendInput{
		Filename:  filepath.Base(nzbFile),
		Content:   base64.StdEncoding.EncodeToString(nzbContent),
		AddToTop:  false,
		AddPaused: true,
		DupeMode:  "SCORE",
		Parameters: []*nzbget.Parameter{
			{Name: "*unpack:", Value: "no"},
		},
	}

	ret, err := nzb.Append(input)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Return Code: %d\n", ret)
}
```

**Comment by davidnewhall** [comment]
Man I musta really been on one; I do not remember writing a full featured library for NZBGet haha. I only use this library to pull active downloads, so all these other methods are quite the bonus. 

I cannot tell off-hand if this is a bug, but it seems to be if the python snippet works.

if it is a bug, it is likely this line:
https://github.com/golift/nzbget/blob/main/methods.go#L411

or the struct it points to:
https://github.com/golift/nzbget/blob/main/output.go#L92-L96

I've never used this method or these parameters, so I just can't be sure what the problem is. My suggestion is to clone this library locally, override it in your go.mod and try to redefine that parameters struct member (first link). A type of `map[string]string` might be a good first thing to try.

**Comment by F4n4t** [comment]
Yes, that's it.
A map doesn't work, but if I use '[][]string', it works.

[["*unpack:","no"]]

**Comment by davidnewhall** [comment]
Sweet. Glad you figured it out so quick! I'll accept a pull request to fix it. :)

**Comment by davidnewhall** [comment]
Does `[][2]string` also work? It may be more appropriate.

**Comment by F4n4t** [comment]
Yes, this also works.
I submitted a pull request (PR). Initially, I thought it would be preferable to simply convert the struct, but now I'm a bit less certain :D

**Comment by davidnewhall** [comment]
What you did was less code than what I was about to do. I like it. Thank you very much!
